//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Curriculum_Entry_Year
    {
        public short Curriculum_Entry_Year_Id { get; set; }
        public short Term_Year_Id { get; set; }
        public short Department_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public short Entry_Year_Id { get; set; }
        public short Curriculum_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<short> Order_Id { get; set; }
    
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Curriculum Mstr_Curriculum { get; set; }
        public virtual Mstr_Department Mstr_Department { get; set; }
        public virtual Mstr_Entry_Year Mstr_Entry_Year { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
