//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Education_History
    {
        public long Education_History_Id { get; set; }
        public long Student_Id { get; set; }
        public Nullable<short> Stage_Education_Id { get; set; }
        public string Title { get; set; }
        public string Certificate_Number { get; set; }
        public Nullable<System.DateTime> Certificate_Date { get; set; }
        public string Certificate_Place { get; set; }
        public Nullable<byte> Certificate_Status { get; set; }
        public string Institution_Name { get; set; }
        public string Faculty { get; set; }
        public string Sks_Old_Institution { get; set; }
        public string Gpa_Old_Institution { get; set; }
        public string Address { get; set; }
        public Nullable<short> City_Id { get; set; }
        public Nullable<short> Country_Id { get; set; }
        public Nullable<short> Number_Of_Course { get; set; }
        public Nullable<short> Program_Type_Id { get; set; }
        public string Acceptance_Year { get; set; }
        public string Completion_Year { get; set; }
        public Nullable<System.DateTime> Completion_Date { get; set; }
        public Nullable<decimal> Nem { get; set; }
        public Nullable<short> Nem_Number { get; set; }
        public string Institution_Id { get; set; }
        public string Graduate_Id { get; set; }
        public string Department { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> Order_Id { get; set; }
    
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Mstr_City Mstr_City { get; set; }
        public virtual Mstr_Country Mstr_Country { get; set; }
    }
}
