//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_Card
    {
        public long Student_Card_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public Nullable<System.DateTime> Print_Card_Date { get; set; }
        public Nullable<short> Print_Card_Times { get; set; }
        public string Officer_Print { get; set; }
        public Nullable<System.DateTime> Receive_Card_Date { get; set; }
        public Nullable<short> Receive_Card_Times { get; set; }
        public string Officer_Receive { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Acd_Student Acd_Student { get; set; }
    }
}
