//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Kinerja
    {
        public long Student_Id { get; set; }
        public byte Term_Id { get; set; }
        public short Year_Id { get; set; }
        public short Course_Id { get; set; }
        public short Available_Edu_Id { get; set; }
        public short Index_Class_Id { get; set; }
        public Nullable<byte> kinerja_dosen_1 { get; set; }
        public Nullable<byte> kinerja_dosen_2 { get; set; }
        public Nullable<byte> kinerja_dosen_3 { get; set; }
        public Nullable<byte> kinerja_dosen_4 { get; set; }
        public Nullable<byte> kinerja_dosen_5 { get; set; }
        public Nullable<byte> kinerja_dosen_6 { get; set; }
        public Nullable<byte> kinerja_dosen_7 { get; set; }
        public Nullable<byte> kinerja_dosen_8 { get; set; }
        public Nullable<byte> kinerja_dosen_9 { get; set; }
        public Nullable<byte> kinerja_dosen_10 { get; set; }
        public Nullable<byte> kinerja_dosen_11 { get; set; }
        public Nullable<byte> kinerja_dosen_12 { get; set; }
        public Nullable<byte> kinerja_dosen_13 { get; set; }
        public Nullable<byte> kinerja_dosen_14 { get; set; }
        public Nullable<byte> kinerja_dosen_15 { get; set; }
        public Nullable<byte> kinerja_dosen_16 { get; set; }
        public Nullable<byte> kinerja_dosen_17 { get; set; }
        public Nullable<byte> kinerja_dosen_18 { get; set; }
        public string kinerja_dosen_saran { get; set; }
        public Nullable<byte> kinerja_akademik_1 { get; set; }
        public Nullable<byte> kinerja_akademik_2 { get; set; }
        public Nullable<byte> kinerja_akademik_3 { get; set; }
        public Nullable<byte> kinerja_akademik_4 { get; set; }
        public Nullable<byte> kinerja_akademik_5 { get; set; }
        public Nullable<byte> kinerja_akademik_6 { get; set; }
        public Nullable<byte> kinerja_akademik_7 { get; set; }
        public Nullable<byte> kinerja_akademik_8 { get; set; }
        public Nullable<byte> kinerja_akademik_9 { get; set; }
        public Nullable<byte> kinerja_akademik_10 { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
