//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Curriculum_EKUIVALENSI_KHS_LAMA
    {
        public string PERUBAHAN_ID { get; set; }
        public short Year_Id { get; set; }
        public byte Term_Id { get; set; }
        public long Student_Id { get; set; }
        public short Course_Id { get; set; }
        public Nullable<short> Faculty_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public short Available_Edu_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public Nullable<int> HASIL_UJIAN_KE { get; set; }
        public string KOMPONEN_NILAI_ID { get; set; }
        public Nullable<decimal> Course_Mark { get; set; }
        public string Grade_Letter { get; set; }
        public Nullable<bool> Is_Tetap { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<decimal> Sks { get; set; }
        public Nullable<decimal> Weight_Value { get; set; }
        public Nullable<bool> Is_Required { get; set; }
        public bool Is_For_Transcript { get; set; }
        public Nullable<System.DateTime> Inserted_Time { get; set; }
    }
}
