//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Sched_Room
    {
        public int Sched_Room_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public short Sched_Type_Id { get; set; }
        public short Room_Id { get; set; }
        public short Department_Id { get; set; }
        public Nullable<short> Class_Prog_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Department Mstr_Department { get; set; }
        public virtual Mstr_Room Mstr_Room { get; set; }
        public virtual Mstr_Sched_Type Mstr_Sched_Type { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
