//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_Khs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acd_Student_Khs()
        {
            this.Acd_Student_KHS_DELETED = new HashSet<Acd_Student_KHS_DELETED>();
            this.Acd_Transcript = new HashSet<Acd_Transcript>();
        }
    
        public long Khs_Id { get; set; }
        public Nullable<long> Krs_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public Nullable<short> Grade_Letter_Id { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<decimal> Weight_Value { get; set; }
        public Nullable<bool> Is_Required { get; set; }
        public bool Is_For_Transkrip { get; set; }
        public Nullable<decimal> Bnk_Value { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
    
        public virtual Acd_Grade_Letter Acd_Grade_Letter { get; set; }
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Acd_Student_Krs Acd_Student_Krs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_KHS_DELETED> Acd_Student_KHS_DELETED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Transcript> Acd_Transcript { get; set; }
    }
}
