//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Transcript
    {
        public long Transcript_Id { get; set; }
        public int Course_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public Nullable<short> Grade_Letter_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public Nullable<short> Exam_Result_For { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<decimal> Sks { get; set; }
        public Nullable<bool> Is_Transfer { get; set; }
        public Nullable<decimal> Weight_Value { get; set; }
        public Nullable<bool> is_Use { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Is_Required { get; set; }
        public Nullable<long> Khs_Id { get; set; }
        public Nullable<decimal> Bnk_Value { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Order_Id { get; set; }
        public string Created_By { get; set; }
    
        public virtual Acd_Course Acd_Course { get; set; }
        public virtual Acd_Grade_Letter Acd_Grade_Letter { get; set; }
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Acd_Student_Khs Acd_Student_Khs { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
