//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Graduation_Final
    {
        public long Student_Id { get; set; }
        public short Graduate_Periode_Id { get; set; }
        public Nullable<long> Certificate_Serial_Num { get; set; }
        public string Certificate_Serial_Sufix { get; set; }
        public string Certificate_Serial_Full { get; set; }
        public string Graduate_Num { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Graduation_Period Acd_Graduation_Period { get; set; }
    }
}
