//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_Parent
    {
        public long Student_Parent_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public short Parent_Type_Id { get; set; }
        public string Full_Name { get; set; }
        public string Kk_Name { get; set; }
        public Nullable<int> Kk { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Birth_Place { get; set; }
        public Nullable<byte> Religion_Id { get; set; }
        public Nullable<short> Education_Type_Id { get; set; }
        public Nullable<byte> Job_Category_Id { get; set; }
        public string Income { get; set; }
        public Nullable<bool> Is_Alive { get; set; }
        public Nullable<bool> Is_Pension { get; set; }
        public string Address { get; set; }
        public Nullable<short> City_Id { get; set; }
        public Nullable<short> Country_Id { get; set; }
        public string Postal_Code { get; set; }
        public string Rt { get; set; }
        public string Rw { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Mstr_City Mstr_City { get; set; }
        public virtual Mstr_Country Mstr_Country { get; set; }
        public virtual Mstr_Education_Type Mstr_Education_Type { get; set; }
        public virtual Mstr_Job_Category Mstr_Job_Category { get; set; }
        public virtual Mstr_Parent_Type Mstr_Parent_Type { get; set; }
        public virtual Mstr_Religion Mstr_Religion { get; set; }
    }
}
