//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Gpa_TEMP
    {
        public long Student_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public Nullable<decimal> Sks_Smt { get; set; }
        public Nullable<decimal> BOBOTSKS_SMT { get; set; }
        public Nullable<decimal> Gpa_Smt { get; set; }
        public Nullable<decimal> Sks_Kum { get; set; }
        public Nullable<decimal> BOBOTSKS_KUM { get; set; }
        public Nullable<decimal> Gpa_Kum { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
    
        public virtual Acd_Student Acd_Student { get; set; }
    }
}
