//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Course_Sched_TIME
    {
        public int Course_Sched_Time_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public short Faculty_Id { get; set; }
        public short Department_Id { get; set; }
        public Nullable<short> Sessi_Id { get; set; }
        public short JAM_KE { get; set; }
        public short Day_Id { get; set; }
        public string Room_Id { get; set; }
        public string Type { get; set; }
        public short Class_Prog_Id { get; set; }
        public int Course_Id { get; set; }
        public short Index_Class_Id { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Order_Id { get; set; }
    }
}
