//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Grade_Department
    {
        public int Grade_Department_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public Nullable<short> Grade_Letter_Id { get; set; }
        public decimal Weight_Value { get; set; }
        public string Predicate { get; set; }
        public string Predicate_Eng { get; set; }
        public Nullable<float> Scale_Numeric_Max { get; set; }
        public Nullable<float> Scale_Numeric_Min { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Order_Id { get; set; }
    
        public virtual Acd_Grade_Letter Acd_Grade_Letter { get; set; }
        public virtual Mstr_Department Mstr_Department { get; set; }
    }
}
