//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_KHS_PRAK_ASISTEN
    {
        public Nullable<short> Term_Year_Id { get; set; }
        public short Course_Id { get; set; }
        public Nullable<short> Faculty_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public short Class_Id { get; set; }
        public Nullable<int> Assistance_Id { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
