//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_KHS_PRAK
    {
        public short Term_Year_Id { get; set; }
        public long Student_Id { get; set; }
        public short Course_Id { get; set; }
        public Nullable<short> Faculty_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public Nullable<short> Class_Prog_Id { get; set; }
        public Nullable<short> NILAI_PRE { get; set; }
        public Nullable<short> NILAI_LAP { get; set; }
        public Nullable<short> NILAI_RES { get; set; }
        public Nullable<decimal> NILAI_AKHIR { get; set; }
        public string NILAI_HURUF { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Acd_Student Acd_Student { get; set; }
    }
}
