//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_Khs_Transfer
    {
        public long Khs_Transfer_Id { get; set; }
        public Nullable<long> Krs_Id { get; set; }
        public Nullable<short> Grade_Letter_Id { get; set; }
        public Nullable<decimal> Weight_Value { get; set; }
        public Nullable<bool> Is_Required { get; set; }
        public bool Is_For_Transkrip { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public Nullable<decimal> Gpa_Semester { get; set; }
        public Nullable<decimal> Bnk_Value { get; set; }
        public short Term_Year_Id { get; set; }
        public int Course_Id { get; set; }
        public short Class_Id { get; set; }
        public decimal Sks { get; set; }
        public Nullable<int> Nb_Taking { get; set; }
        public Nullable<System.DateTime> Krs_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public string Course_Name_Old { get; set; }
        public string Course_Name { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Acd_Course Acd_Course { get; set; }
        public virtual Acd_Grade_Letter Acd_Grade_Letter { get; set; }
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Acd_Student_Krs Acd_Student_Krs { get; set; }
        public virtual Mstr_Class Mstr_Class { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
