//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Course_Sched_Description
    {
        public int Crs_Sched_Desc_Id { get; set; }
        public Nullable<int> Course_Sched_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Order_Id { get; set; }
    
        public virtual Acd_Course_Sched Acd_Course_Sched { get; set; }
    }
}
