//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_Krs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acd_Student_Krs()
        {
            this.Acd_Student_Khs = new HashSet<Acd_Student_Khs>();
            this.Acd_Student_Khs_Transfer = new HashSet<Acd_Student_Khs_Transfer>();
        }
    
        public long Krs_Id { get; set; }
        public long Student_Id { get; set; }
        public short Term_Year_Id { get; set; }
        public int Course_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public short Class_Id { get; set; }
        public decimal Sks { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Nb_Taking { get; set; }
        public Nullable<System.DateTime> Krs_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<short> Cost_Item_Id { get; set; }
        public Nullable<bool> Is_Approved { get; set; }
        public Nullable<bool> Is_Locked { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Order_Id { get; set; }
        public string Created_By { get; set; }
    
        public virtual Acd_Course Acd_Course { get; set; }
        public virtual Acd_Student Acd_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Khs> Acd_Student_Khs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Khs_Transfer> Acd_Student_Khs_Transfer { get; set; }
        public virtual Fnc_Cost_Item Fnc_Cost_Item { get; set; }
        public virtual Mstr_Class Mstr_Class { get; set; }
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
