//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Research
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_Research()
        {
            this.Emp_Research_Document = new HashSet<Emp_Research_Document>();
        }
    
        public int Research_Id { get; set; }
        public int Employee_Id { get; set; }
        public string Title { get; set; }
        public decimal Total_Fund { get; set; }
        public byte Source_Fund_Id { get; set; }
        public short Start_Year { get; set; }
        public short End_Year { get; set; }
        public string Cover_Page { get; set; }
        public string Cover_Page_Ext { get; set; }
        public string Validation_Page { get; set; }
        public string Validation_Page_Ext { get; set; }
        public string Table_Of_Content_Page { get; set; }
        public string Table_Of_Content_Page_Ext { get; set; }
        public string First_Page_Content { get; set; }
        public string First_Page_Content_Ext { get; set; }
        public int Parent_Id { get; set; }
        public string External_Member { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Research_Document> Emp_Research_Document { get; set; }
        public virtual Mstr_Source_Fund Mstr_Source_Fund { get; set; }
    }
}
