//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_akses_log
    {
        public int id { get; set; }
        public string email { get; set; }
        public string ip_address { get; set; }
        public System.DateTime tanggal { get; set; }
        public string browser { get; set; }
        public string tipe_akses { get; set; }
        public string url { get; set; }
    }
}
