//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Employee_Family
    {
        public int Employee_Family_Id { get; set; }
        public int Employee_Id { get; set; }
        public string Name { get; set; }
        public string Birth_Place { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public Nullable<byte> Gender_Id { get; set; }
        public Nullable<byte> Religion_Id { get; set; }
        public Nullable<int> Identity_Type_Id { get; set; }
        public string Identity_Num { get; set; }
        public Nullable<int> Family_Relation_Id { get; set; }
        public Nullable<short> Stage_Education_Id { get; set; }
        public bool Is_Rice_Allowance { get; set; }
        public bool Is_Hospitalization_Reduction { get; set; }
        public bool Is_Family_Allowance { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Emp_Family_Relation Emp_Family_Relation { get; set; }
        public virtual Mstr_Stage_Education Mstr_Stage_Education { get; set; }
        public virtual Emp_Identity_Type Emp_Identity_Type { get; set; }
        public virtual Mstr_Gender Mstr_Gender { get; set; }
        public virtual Mstr_Religion Mstr_Religion { get; set; }
    }
}
