//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Teach_Kbk_Count_Resume
    {
        public int Teach_Kbk_Count_Resume_Id { get; set; }
        public short Term_Year_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Month { get; set; }
        public Nullable<decimal> Bruto_Income { get; set; }
        public Nullable<decimal> Pph { get; set; }
        public Nullable<decimal> Infaq { get; set; }
        public Nullable<decimal> Reduction { get; set; }
        public string Reduction_Description { get; set; }
        public Nullable<decimal> Other_Income { get; set; }
        public Nullable<decimal> Netto { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
    }
}
