//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Journal
    {
        public int Journal_Id { get; set; }
        public int Employee_Id { get; set; }
        public Nullable<short> Year_Id { get; set; }
        public string Title { get; set; }
        public string Journal_Name { get; set; }
        public string Volue { get; set; }
        public string Issn { get; set; }
        public string Leader_Name { get; set; }
        public string Member_Name { get; set; }
        public string Abstract_File { get; set; }
        public string Abstract_Ext { get; set; }
        public string Full_Document_File { get; set; }
        public string Full_Document_Ext { get; set; }
        public string Website { get; set; }
        public string Cover { get; set; }
        public string Cover_Ext { get; set; }
        public string Table_Of_Content { get; set; }
        public string Table_Of_Content_Ext { get; set; }
        public string First_Page_Content { get; set; }
        public string First_Page_Content_Ext { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Mstr_Entry_Year Mstr_Entry_Year { get; set; }
    }
}
