//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fnc_Cost_Sched_Detail
    {
        public int Cost_Sched_Detail_Id { get; set; }
        public int Cost_Sched_Id { get; set; }
        public short Cost_Item_id { get; set; }
        public int Amount { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Fnc_Cost_Item Fnc_Cost_Item { get; set; }
        public virtual Fnc_Cost_Sched Fnc_Cost_Sched { get; set; }
    }
}
