//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fnc_Student_Payment
    {
        public long Student_Payment_Id { get; set; }
        public Nullable<long> Reff_Payment_Id { get; set; }
        public Nullable<short> Trans_Order { get; set; }
        public short Term_Year_Id { get; set; }
        public string Register_Number { get; set; }
        public short Cost_Item_Id { get; set; }
        public Nullable<short> Installment_Order { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public string Payment_Status { get; set; }
        public Nullable<short> Cashier_Id { get; set; }
        public string Bank_Id { get; set; }
        public Nullable<System.DateTime> Print_Date { get; set; }
        public Nullable<short> Term_Year_Bill_Id { get; set; }
        public Nullable<short> Bill_Type_Id { get; set; }
        public string Descripton { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Fnc_Bank Fnc_Bank { get; set; }
        public virtual Fnc_Bill_Type Fnc_Bill_Type { get; set; }
        public virtual Fnc_Cost_Item Fnc_Cost_Item { get; set; }
        public virtual Fnc_Reff_Payment Fnc_Reff_Payment { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
