//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fnc_Cost_Krs_Personal
    {
        public long Cost_Krs_Personal_Id { get; set; }
        public short Term_Year_Id { get; set; }
        public long Student_Id { get; set; }
        public short Course_Type_Id { get; set; }
        public Nullable<short> Dispen_Type_Id { get; set; }
        public Nullable<decimal> Cost_Percent { get; set; }
        public Nullable<bool> Is_Pending { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Description { get; set; }
        public string Sk_Num { get; set; }
        public Nullable<System.DateTime> Sk_Date { get; set; }
        public string Functionary_Sk { get; set; }
        public string Functionary_Name { get; set; }
        public string Functionary_Nik { get; set; }
        public string Created_By { get; set; }
        public string Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Course_Type Acd_Course_Type { get; set; }
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Mstr_Dispen_Type Mstr_Dispen_Type { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
