//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Entry_Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mstr_Entry_Period()
        {
            this.Acd_Student = new HashSet<Acd_Student>();
        }
    
        public short Entry_Period_Id { get; set; }
        public string Entry_Period_Code { get; set; }
        public string Period_Name { get; set; }
        public short Entry_Year_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Start_Registration { get; set; }
        public Nullable<System.DateTime> End_Registration { get; set; }
        public Nullable<System.DateTime> Announcement_Date { get; set; }
        public Nullable<System.DateTime> Start_Herregistration { get; set; }
        public Nullable<System.DateTime> End_Herregistration { get; set; }
        public Nullable<short> Entry_Period_Type_Id { get; set; }
        public Nullable<System.DateTime> Start_Date2 { get; set; }
        public Nullable<System.DateTime> End_Date2 { get; set; }
        public Nullable<System.DateTime> Test_Date2 { get; set; }
        public Nullable<byte> Order_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student> Acd_Student { get; set; }
        public virtual Mstr_Entry_Period_Type Mstr_Entry_Period_Type { get; set; }
    }
}
