//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Concentration
    {
        public short Concentration_Id { get; set; }
        public string Concentration_Code { get; set; }
        public short Department_Id { get; set; }
        public string Concentration_Name { get; set; }
        public string Concentration_Name_Eng { get; set; }
        public string Concentration_Acronym { get; set; }
        public Nullable<byte> Order_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Mstr_Department Mstr_Department { get; set; }
    }
}
