//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Class_Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mstr_Class_Program()
        {
            this.Acd_App_Sk = new HashSet<Acd_App_Sk>();
            this.Acd_Course_Classical = new HashSet<Acd_Course_Classical>();
            this.Acd_Course_Curriculum = new HashSet<Acd_Course_Curriculum>();
            this.Acd_Course_Sched = new HashSet<Acd_Course_Sched>();
            this.Acd_Curriculum_Entry_Year = new HashSet<Acd_Curriculum_Entry_Year>();
            this.Acd_Exam_Sched = new HashSet<Acd_Exam_Sched>();
            this.Acd_Offered_Course = new HashSet<Acd_Offered_Course>();
            this.Acd_Sched_Real = new HashSet<Acd_Sched_Real>();
            this.Acd_Sched_Room = new HashSet<Acd_Sched_Room>();
            this.Acd_Sk_Publish = new HashSet<Acd_Sk_Publish>();
            this.Acd_Student = new HashSet<Acd_Student>();
            this.Acd_Student_KHS_DELETED = new HashSet<Acd_Student_KHS_DELETED>();
            this.Acd_Student_Krs = new HashSet<Acd_Student_Krs>();
            this.Acd_Student_Out = new HashSet<Acd_Student_Out>();
            this.Acd_Student_Out1 = new HashSet<Acd_Student_Out>();
            this.Emp_Teach_Kbk = new HashSet<Emp_Teach_Kbk>();
            this.Emp_Teach_Kbk_Count = new HashSet<Emp_Teach_Kbk_Count>();
            this.Fnc_Cost_Regular = new HashSet<Fnc_Cost_Regular>();
            this.Fnc_Cost_Regular_Up = new HashSet<Fnc_Cost_Regular_Up>();
            this.Fnc_Cost_Sched = new HashSet<Fnc_Cost_Sched>();
            this.Fnc_Cost_Timing = new HashSet<Fnc_Cost_Timing>();
            this.Fnc_Course_Cost_Sks = new HashSet<Fnc_Course_Cost_Sks>();
            this.Fnc_Course_Cost_Type = new HashSet<Fnc_Course_Cost_Type>();
            this.Mstr_Curriculum_Applied = new HashSet<Mstr_Curriculum_Applied>();
            this.Mstr_Department_Class_Program = new HashSet<Mstr_Department_Class_Program>();
            this.Mstr_Department_Event_Sched = new HashSet<Mstr_Department_Event_Sched>();
        }
    
        public short Class_Prog_Id { get; set; }
        public string Class_Prog_Code { get; set; }
        public string Class_Program_Name { get; set; }
        public string Class_Program_Name_Eng { get; set; }
        public Nullable<byte> Order_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_App_Sk> Acd_App_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Classical> Acd_Course_Classical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Curriculum> Acd_Course_Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Sched> Acd_Course_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Curriculum_Entry_Year> Acd_Curriculum_Entry_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Exam_Sched> Acd_Exam_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course> Acd_Offered_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Real> Acd_Sched_Real { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Room> Acd_Sched_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sk_Publish> Acd_Sk_Publish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student> Acd_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_KHS_DELETED> Acd_Student_KHS_DELETED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Krs> Acd_Student_Krs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Out> Acd_Student_Out { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Out> Acd_Student_Out1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Teach_Kbk> Emp_Teach_Kbk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Teach_Kbk_Count> Emp_Teach_Kbk_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular> Fnc_Cost_Regular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular_Up> Fnc_Cost_Regular_Up { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Sched> Fnc_Cost_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Timing> Fnc_Cost_Timing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Course_Cost_Sks> Fnc_Course_Cost_Sks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Course_Cost_Type> Fnc_Course_Cost_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Curriculum_Applied> Mstr_Curriculum_Applied { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Department_Class_Program> Mstr_Department_Class_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Department_Event_Sched> Mstr_Department_Event_Sched { get; set; }
    }
}
