//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mstr_Faculty()
        {
            this.Acd_App_Sk = new HashSet<Acd_App_Sk>();
            this.Acd_Course_Classical = new HashSet<Acd_Course_Classical>();
            this.Acd_Sk_Publish = new HashSet<Acd_Sk_Publish>();
            this.Mstr_Department = new HashSet<Mstr_Department>();
        }
    
        public short Faculty_Id { get; set; }
        public string Faculty_Code { get; set; }
        public string Faculty_Name { get; set; }
        public string Faculty_Name_Eng { get; set; }
        public string Faculty_Acronym { get; set; }
        public Nullable<int> Dean_Id { get; set; }
        public Nullable<int> Dean_1_Id { get; set; }
        public Nullable<int> Dean_2_Id { get; set; }
        public Nullable<int> Dean_3_Id { get; set; }
        public Nullable<int> Secertary_Id { get; set; }
        public Nullable<byte> Order_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_App_Sk> Acd_App_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Classical> Acd_Course_Classical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sk_Publish> Acd_Sk_Publish { get; set; }
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Emp_Employee Emp_Employee1 { get; set; }
        public virtual Emp_Employee Emp_Employee2 { get; set; }
        public virtual Emp_Employee Emp_Employee3 { get; set; }
        public virtual Emp_Employee Emp_Employee4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Department> Mstr_Department { get; set; }
    }
}
