//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_User
    {
        public string User_Id { get; set; }
        public string Full_Name { get; set; }
        public string Employee_Id { get; set; }
        public string Description { get; set; }
        public byte[] Password { get; set; }
        public string Must_Change { get; set; }
        public Nullable<System.DateTime> Expired_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Nip { get; set; }
        public string Bank_Id { get; set; }
        public string Branch_Id { get; set; }
        public Nullable<System.DateTime> First_Created { get; set; }
        public Nullable<System.DateTime> Last_Modified { get; set; }
        public string User_Created { get; set; }
        public string User_Modified { get; set; }
        public string Email { get; set; }
    }
}
