//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Term_Year
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mstr_Term_Year()
        {
            this.Acd_App_Sk = new HashSet<Acd_App_Sk>();
            this.Acd_Class_Lecturer = new HashSet<Acd_Class_Lecturer>();
            this.Acd_Course_Classical = new HashSet<Acd_Course_Classical>();
            this.Acd_Curriculum_Entry_Year = new HashSet<Acd_Curriculum_Entry_Year>();
            this.Acd_Exam_Sched = new HashSet<Acd_Exam_Sched>();
            this.Acd_Graduation_Period = new HashSet<Acd_Graduation_Period>();
            this.Acd_Offered_Course = new HashSet<Acd_Offered_Course>();
            this.Acd_Sched_Real = new HashSet<Acd_Sched_Real>();
            this.Acd_Sched_Room = new HashSet<Acd_Sched_Room>();
            this.Acd_Sched_Session = new HashSet<Acd_Sched_Session>();
            this.Acd_Sched_Session1 = new HashSet<Acd_Sched_Session>();
            this.Acd_Sk_Publish = new HashSet<Acd_Sk_Publish>();
            this.Acd_Student_Card_Temporary = new HashSet<Acd_Student_Card_Temporary>();
            this.Acd_Student_History = new HashSet<Acd_Student_History>();
            this.Acd_Student_Khs_Transfer = new HashSet<Acd_Student_Khs_Transfer>();
            this.Acd_Student_Krs = new HashSet<Acd_Student_Krs>();
            this.Acd_Student_Out = new HashSet<Acd_Student_Out>();
            this.Acd_Thesis = new HashSet<Acd_Thesis>();
            this.Acd_Thesis1 = new HashSet<Acd_Thesis>();
            this.Acd_Transcript = new HashSet<Acd_Transcript>();
            this.Acd_Yudisium = new HashSet<Acd_Yudisium>();
            this.Emp_Teach_Kbk = new HashSet<Emp_Teach_Kbk>();
            this.Emp_Teach_Kbk_Count = new HashSet<Emp_Teach_Kbk_Count>();
            this.Fnc_Cost_Krs_Personal = new HashSet<Fnc_Cost_Krs_Personal>();
            this.Fnc_Cost_Regular = new HashSet<Fnc_Cost_Regular>();
            this.Fnc_Cost_Regular_Personal = new HashSet<Fnc_Cost_Regular_Personal>();
            this.Fnc_Cost_Regular_Personal_Up = new HashSet<Fnc_Cost_Regular_Personal_Up>();
            this.Fnc_Cost_Regular_Up = new HashSet<Fnc_Cost_Regular_Up>();
            this.Fnc_Cost_Sched = new HashSet<Fnc_Cost_Sched>();
            this.Fnc_Cost_Timing = new HashSet<Fnc_Cost_Timing>();
            this.Fnc_Cost_Timing_Personal = new HashSet<Fnc_Cost_Timing_Personal>();
            this.Fnc_Course_Cost_Sks = new HashSet<Fnc_Course_Cost_Sks>();
            this.Fnc_Course_Cost_Type = new HashSet<Fnc_Course_Cost_Type>();
            this.Fnc_Reff_Payment = new HashSet<Fnc_Reff_Payment>();
            this.Fnc_Student_Payment = new HashSet<Fnc_Student_Payment>();
            this.Mstr_Department_Event_Sched = new HashSet<Mstr_Department_Event_Sched>();
        }
    
        public short Term_Year_Id { get; set; }
        public short Year_Id { get; set; }
        public byte Term_Id { get; set; }
        public string Term_Year_Name { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_App_Sk> Acd_App_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Class_Lecturer> Acd_Class_Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Classical> Acd_Course_Classical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Curriculum_Entry_Year> Acd_Curriculum_Entry_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Exam_Sched> Acd_Exam_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Graduation_Period> Acd_Graduation_Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course> Acd_Offered_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Real> Acd_Sched_Real { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Room> Acd_Sched_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Session> Acd_Sched_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Session> Acd_Sched_Session1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sk_Publish> Acd_Sk_Publish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Card_Temporary> Acd_Student_Card_Temporary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_History> Acd_Student_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Khs_Transfer> Acd_Student_Khs_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Krs> Acd_Student_Krs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Out> Acd_Student_Out { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Thesis> Acd_Thesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Thesis> Acd_Thesis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Transcript> Acd_Transcript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Yudisium> Acd_Yudisium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Teach_Kbk> Emp_Teach_Kbk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Teach_Kbk_Count> Emp_Teach_Kbk_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Krs_Personal> Fnc_Cost_Krs_Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular> Fnc_Cost_Regular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular_Personal> Fnc_Cost_Regular_Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular_Personal_Up> Fnc_Cost_Regular_Personal_Up { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular_Up> Fnc_Cost_Regular_Up { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Sched> Fnc_Cost_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Timing> Fnc_Cost_Timing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Timing_Personal> Fnc_Cost_Timing_Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Course_Cost_Sks> Fnc_Course_Cost_Sks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Course_Cost_Type> Fnc_Course_Cost_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Reff_Payment> Fnc_Reff_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Student_Payment> Fnc_Student_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Department_Event_Sched> Mstr_Department_Event_Sched { get; set; }
        public virtual Mstr_Entry_Year Mstr_Entry_Year { get; set; }
        public virtual Mstr_Term Mstr_Term { get; set; }
    }
}
