//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTIONS
    {
        public int OPTION_ID { get; set; }
        public string AVAILABLE_EDU_ID { get; set; }
        public string CLASSPROG_ID { get; set; }
        public Nullable<short> SMT_PDK_MK_MAX { get; set; }
        public Nullable<short> SMT_PDK_SKS_MAX { get; set; }
        public Nullable<short> SMT_PDK_ISULANG { get; set; }
        public string SMT_PDK_NILAI_MIN { get; set; }
        public Nullable<short> SMT_PDK_ISAKTIF { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<short> SMT_REM1_MK_MAX { get; set; }
        public Nullable<short> SMT_REM1_SKS_MAX { get; set; }
        public Nullable<short> SMT_REM1_ISULANG { get; set; }
        public string SMT_REM1_NILAI_MIN { get; set; }
        public Nullable<short> SMT_REM1_ISALLTHN { get; set; }
        public string SMT_REM1_SMT_ULANG { get; set; }
        public Nullable<short> SMT_REM2_MK_MAX { get; set; }
        public Nullable<short> SMT_REM2_SKS_MAX { get; set; }
        public Nullable<short> SMT_REM2_ISULANG { get; set; }
        public string SMT_REM2_NILAI_MIN { get; set; }
        public Nullable<short> SMT_REM2_ISALLTHN { get; set; }
        public string SMT_REM2_SMT_ULANG { get; set; }
    }
}
