//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Offered_GROUP_TEST
    {
        public short Education_Group_Id { get; set; }
        public string Materi_Test_Id { get; set; }
        public short Entry_Period_Id { get; set; }
        public short Year_Id { get; set; }
        public string GROUP_ID { get; set; }
        public float Group_Weight { get; set; }
        public Nullable<short> Questions_Num { get; set; }
        public Nullable<short> Group_Order { get; set; }
    }
}
