//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Camaru_Education_HISTORY
    {
        public long Camaru_History_Id { get; set; }
        public short Year_Id { get; set; }
        public long Camaru_Id { get; set; }
        public short Education_History_Id { get; set; }
        public string Pk_Education_Type { get; set; }
        public string Title { get; set; }
        public string Institution_Name { get; set; }
        public string Address { get; set; }
        public Nullable<short> City_Id { get; set; }
        public Nullable<short> Province_Id { get; set; }
        public Nullable<short> Country_Id { get; set; }
        public Nullable<decimal> Postal_Code { get; set; }
        public Nullable<decimal> Grade_Number { get; set; }
        public Nullable<int> Year_Of_Acceptance { get; set; }
        public Nullable<int> Year_Of_Completion { get; set; }
        public string High_School_Major_Id { get; set; }
        public string Institution_Id { get; set; }
        public string Certificate_Id { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
