//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Tahap_MASUK_
    {
        public short Year_Id { get; set; }
        public string Register_Type_Id { get; set; }
        public short TAHAP_KE { get; set; }
        public string NAMA_TAHAP_MASUK { get; set; }
        public Nullable<System.DateTime> Registration_Start_Date { get; set; }
        public Nullable<System.DateTime> Registration_End_Date { get; set; }
        public Nullable<System.DateTime> Announcement_Date { get; set; }
        public Nullable<System.DateTime> Prareg_Start_Date { get; set; }
        public Nullable<System.DateTime> Prareg_End_Date { get; set; }
        public Nullable<System.DateTime> Reg_Start_Date { get; set; }
        public Nullable<System.DateTime> Reg_End_Date { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
