//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Access_RIGHT
    {
        public string Access_Right_Id { get; set; }
        public short Faculty_Id { get; set; }
        public short Department_Id { get; set; }
        public short Available_Edu_Id { get; set; }
    }
}
