//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_KEU_MHS_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_z_Group_Program_Choice
    {
        public string Group_Program_id { get; set; }
        public string GP_Choice_id { get; set; }
        public string Nama_GP_Choice { get; set; }
    }
}
