//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Exam_Sched
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acd_Exam_Sched()
        {
            this.Acd_Exam_Sched_Detail = new HashSet<Acd_Exam_Sched_Detail>();
        }
    
        public short Exam_Sched_Id { get; set; }
        public short Term_Year_Id { get; set; }
        public short Exam_Type_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public int Course_Id { get; set; }
        public short Class_Id { get; set; }
        public short Room_Num { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }
        public Nullable<System.DateTime> Exam_Time_1 { get; set; }
        public Nullable<System.DateTime> Exam_Time_2 { get; set; }
        public Nullable<short> Room_Id { get; set; }
        public Nullable<int> Supervisor_1_Id { get; set; }
        public Nullable<int> Supervisor_2_Id { get; set; }
        public Nullable<int> Supervisor_3_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Course Acd_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Exam_Sched_Detail> Acd_Exam_Sched_Detail { get; set; }
        public virtual Mstr_Class Mstr_Class { get; set; }
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Exam_Type Mstr_Exam_Type { get; set; }
        public virtual Mstr_Room Mstr_Room { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
