//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Sched_Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acd_Sched_Session()
        {
            this.Acd_Course_Sched = new HashSet<Acd_Course_Sched>();
            this.Acd_Offered_Course_Sched = new HashSet<Acd_Offered_Course_Sched>();
        }
    
        public short Sched_Session_Id { get; set; }
        public short Sched_Type_Id { get; set; }
        public short Term_Year_Id { get; set; }
        public short Day_Id { get; set; }
        public Nullable<short> Class_Prog_Id { get; set; }
        public Nullable<short> Order_Id { get; set; }
        public string Time_Start { get; set; }
        public string Time_End { get; set; }
        public string Description { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Sched> Acd_Course_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course_Sched> Acd_Offered_Course_Sched { get; set; }
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Day Mstr_Day { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
        public virtual Mstr_Sched_Type Mstr_Sched_Type { get; set; }
    }
}
