//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Yudisium
    {
        public long Student_Id { get; set; }
        public short Term_Year_Id { get; set; }
        public Nullable<decimal> Sks_Total { get; set; }
        public Nullable<byte> Course_Count { get; set; }
        public Nullable<decimal> Bnk { get; set; }
        public Nullable<decimal> Gpa { get; set; }
        public string Sk_Num { get; set; }
        public Nullable<System.DateTime> Sk_Date { get; set; }
        public Nullable<System.DateTime> Yudisium_Date { get; set; }
        public Nullable<System.DateTime> Graduate_Date { get; set; }
        public Nullable<System.DateTime> Application_Date { get; set; }
        public Nullable<bool> Is_Graduated { get; set; }
        public Nullable<short> Graduate_Predicate_Id { get; set; }
        public string Transcript_Num { get; set; }
        public Nullable<System.DateTime> Transcript_Date { get; set; }
        public string Department_Functionary { get; set; }
        public string Department_Functionary_Name { get; set; }
        public string Department_Functionary_Nik { get; set; }
        public string Faculty_Functionary { get; set; }
        public string Faculty_Functionary_Name { get; set; }
        public string Faculty_Functionary_Nik { get; set; }
        public string Description { get; set; }
        public Nullable<short> Graduation_Period_Id { get; set; }
        public Nullable<short> Age_Year { get; set; }
        public Nullable<short> Age_Month { get; set; }
        public Nullable<short> Age_Day { get; set; }
        public Nullable<decimal> Age_Year_Length { get; set; }
        public Nullable<int> Age_Day_Length { get; set; }
        public Nullable<short> Study_Length_Year { get; set; }
        public Nullable<short> Study_Length_Month { get; set; }
        public Nullable<short> Study_Length_Day { get; set; }
        public Nullable<decimal> Study_Length_Sum_Year { get; set; }
        public Nullable<short> Study_Length_Sum_Day { get; set; }
        public Nullable<byte> Study_Smt_Length { get; set; }
        public Nullable<byte> Study_Smt_Off_Length { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> Order_Id { get; set; }
    
        public virtual Acd_Graduation_Period Acd_Graduation_Period { get; set; }
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Mstr_Graduate_Predicate Mstr_Graduate_Predicate { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
