//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Offered_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acd_Offered_Course()
        {
            this.Acd_Offered_Course_Lecturer = new HashSet<Acd_Offered_Course_Lecturer>();
            this.Acd_Offered_Course_Sched = new HashSet<Acd_Offered_Course_Sched>();
        }
    
        public int Offered_Course_id { get; set; }
        public short Term_Year_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public Nullable<short> Class_Prog_Id { get; set; }
        public int Course_Id { get; set; }
        public short Class_Id { get; set; }
        public Nullable<short> Total_Meeting { get; set; }
        public Nullable<short> Class_Capacity { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Course Acd_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course_Lecturer> Acd_Offered_Course_Lecturer { get; set; }
        public virtual Mstr_Class Mstr_Class { get; set; }
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Department Mstr_Department { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course_Sched> Acd_Offered_Course_Sched { get; set; }
    }
}
