//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_GPA_SKS
    {
        public short Faculty_Id { get; set; }
        public short Department_Id { get; set; }
        public int SKS_JATAH_GPA { get; set; }
        public Nullable<decimal> Upper_Bound_GPA { get; set; }
        public Nullable<decimal> Lower_Bound_GPA { get; set; }
        public Nullable<int> Sks_Quota { get; set; }
        public Nullable<decimal> Dispensation_Id { get; set; }
        public Nullable<bool> Is_Money { get; set; }
        public Nullable<decimal> JATAHSKS_DISPENSASI { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
