//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Student_3_24_
    {
        public string Nim { get; set; }
        public string Full_Name { get; set; }
        public string Class_Program_Name { get; set; }
        public string Department_Name { get; set; }
        public string Gender_Type { get; set; }
        public string Faculty_Name { get; set; }
        public string Blood_Type { get; set; }
        public string Citizenship_Name { get; set; }
        public string Job_Category_Name { get; set; }
        public string Marital_Status_Type { get; set; }
        public string Register_Status_Name { get; set; }
        public string Period_Name { get; set; }
        public string Entry_Period_Type_Name { get; set; }
        public string Term_Year_Name { get; set; }
    }
}
