//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Sched_Real
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acd_Sched_Real()
        {
            this.Acd_Student_Sched = new HashSet<Acd_Student_Sched>();
        }
    
        public int Sched_Real_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public int Course_Id { get; set; }
        public short Class_Id { get; set; }
        public Nullable<short> Meeting_Order { get; set; }
        public Nullable<short> Room_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time_Start { get; set; }
        public string Time_End { get; set; }
        public string Token { get; set; }
        public string Course_Content { get; set; }
        public string Closed_By { get; set; }
        public Nullable<short> Max_Minutes { get; set; }
        public string Description { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Course Acd_Course { get; set; }
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Emp_Employee Emp_Employee1 { get; set; }
        public virtual Mstr_Class Mstr_Class { get; set; }
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Room Mstr_Room { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Sched> Acd_Student_Sched { get; set; }
    }
}
