//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_INTERNSHIP
    {
        public long Internship_Id { get; set; }
        public long Student_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public Nullable<short> Course_Id { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<decimal> Sks_Trough { get; set; }
        public Nullable<decimal> Bnk { get; set; }
        public string NO_IJIN_CARI_LOK { get; set; }
        public Nullable<System.DateTime> TGL_IJIN_CARI_LOK { get; set; }
        public string NO_IJIN_KP { get; set; }
        public Nullable<System.DateTime> TGL_IJIN_KP { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public string JAB_PIMP_PERUSH { get; set; }
        public string CQ_PIMP_PERUSH { get; set; }
        public string Supervision { get; set; }
        public string NAMA_DOSEN_BIMB { get; set; }
        public string NO_SRT_SETUJU { get; set; }
        public Nullable<System.DateTime> TGL_SRT_SETUJU { get; set; }
        public string NO_SRT_TGS_KP { get; set; }
        public Nullable<System.DateTime> TGL_SRT_TGS_KP { get; set; }
        public string LAMA_KP_TEKS { get; set; }
        public Nullable<System.DateTime> TGL_KP_MULAI { get; set; }
        public Nullable<System.DateTime> TGL_KP_SELESAI { get; set; }
        public Nullable<System.DateTime> TGL_MOHON_SEMINAR { get; set; }
        public Nullable<System.DateTime> TGL_SEMINAR { get; set; }
        public string JUDUL_SEMINAR { get; set; }
        public string RUANG_SEMINAR { get; set; }
        public Nullable<short> JML_PST_SEMINAR { get; set; }
        public string NILAI_SEMINAR { get; set; }
        public string CATATAN_SEMINAR { get; set; }
        public string PJB_JURUSAN { get; set; }
        public string NAMA_PJB_JURUSAN { get; set; }
        public string Code { get; set; }
        public string Project_Name { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Student Acd_Student { get; set; }
    }
}
