//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Curriculum_PERUBAHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acd_Curriculum_PERUBAHAN()
        {
            this.Acd_Curriculum_EKUIVALENSI = new HashSet<Acd_Curriculum_EKUIVALENSI>();
            this.Acd_Curriculum_EKUIVALENSI_TRANSKRIP = new HashSet<Acd_Curriculum_EKUIVALENSI_TRANSKRIP>();
        }
    
        public string PERUBAHAN_ID { get; set; }
        public short Available_Edu_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public Nullable<short> Year_Id { get; set; }
        public byte Term_Id { get; set; }
        public short Curriculum_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Curriculum_EKUIVALENSI> Acd_Curriculum_EKUIVALENSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Curriculum_EKUIVALENSI_TRANSKRIP> Acd_Curriculum_EKUIVALENSI_TRANSKRIP { get; set; }
        public virtual Mstr_Curriculum Mstr_Curriculum { get; set; }
    }
}
