//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Course_Classical
    {
        public int Course_Classical_Id { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public short Faculty_Id { get; set; }
        public short Department_Id { get; set; }
        public short Sessi_Id { get; set; }
        public short Day_Id { get; set; }
        public short Room_Id { get; set; }
        public short Class_Prog_Id { get; set; }
        public int Course_Id { get; set; }
        public string Description { get; set; }
        public short Class_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<short> Order_Id { get; set; }
    
        public virtual Acd_Course Acd_Course { get; set; }
        public virtual Mstr_Class Mstr_Class { get; set; }
        public virtual Mstr_Class_Program Mstr_Class_Program { get; set; }
        public virtual Mstr_Day Mstr_Day { get; set; }
        public virtual Mstr_Department Mstr_Department { get; set; }
        public virtual Mstr_Faculty Mstr_Faculty { get; set; }
        public virtual Mstr_Room Mstr_Room { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
    }
}
