//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acd_Graduation_Reg
    {
        public long Graduation_Reg_Id { get; set; }
        public short Graduation_Periode_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public Nullable<short> Age_Year { get; set; }
        public Nullable<short> Age_Month { get; set; }
        public Nullable<short> Age_Day { get; set; }
        public Nullable<decimal> Age_Year_Length { get; set; }
        public Nullable<int> Age_Day_Length { get; set; }
        public Nullable<short> Study_Length_Year { get; set; }
        public Nullable<short> Study_Length_Month { get; set; }
        public Nullable<short> Study_Length_Day { get; set; }
        public Nullable<decimal> Study_Length_Sum_Year { get; set; }
        public Nullable<short> Study_Length_Sum_Day { get; set; }
        public Nullable<short> Total_Smt_Vacation { get; set; }
        public Nullable<short> Total_Smt_Study { get; set; }
        public Nullable<short> Register_Status_Id { get; set; }
        public Nullable<short> Graduate_Predicate_Id { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Acd_Graduation_Period Acd_Graduation_Period { get; set; }
        public virtual Acd_Student Acd_Student { get; set; }
        public virtual Mstr_Graduate_Predicate Mstr_Graduate_Predicate { get; set; }
        public virtual Mstr_Register_Status Mstr_Register_Status { get; set; }
    }
}
