//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_LOGIN_LOG
    {
        public long Row_Id { get; set; }
        public long Student_Id { get; set; }
        public Nullable<System.DateTime> Login_Time { get; set; }
        public Nullable<bool> Is_Succeed { get; set; }
        public string Status { get; set; }
    }
}
