//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Employee_Structural
    {
        public int Employee_Structural_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Position_Structural_Id { get; set; }
        public int Work_Unit_Id { get; set; }
        public string Sk_Num { get; set; }
        public Nullable<System.DateTime> Sk_Date { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public Nullable<double> Structural_Allowance { get; set; }
        public Nullable<double> Unit_Allowance { get; set; }
        public string File_Name { get; set; }
        public string File_Ext { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Emp_Position_Structural Emp_Position_Structural { get; set; }
        public virtual Emp_Work_Unit Emp_Work_Unit { get; set; }
    }
}
