//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Handbook
    {
        public int Handbook_Id { get; set; }
        public int Employee_Id { get; set; }
        public string Title { get; set; }
        public string Writer { get; set; }
        public Nullable<int> Total_Page { get; set; }
        public string Publisher { get; set; }
        public string Isbn { get; set; }
        public string City { get; set; }
        public string Course { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
    }
}
