//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Employee_Functional
    {
        public int Employee_Functional_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Functional_Position_Id { get; set; }
        public string Sk_Num { get; set; }
        public Nullable<System.DateTime> Sk_Date { get; set; }
        public Nullable<System.DateTime> Valid_Date { get; set; }
        public string File_Name { get; set; }
        public string File_Ext { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Emp_Functional_Position Emp_Functional_Position { get; set; }
    }
}
