//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_Employee()
        {
            this.Acd_Class_Lecturer = new HashSet<Acd_Class_Lecturer>();
            this.Acd_Course_Lecturer = new HashSet<Acd_Course_Lecturer>();
            this.Acd_Department_Lecturer = new HashSet<Acd_Department_Lecturer>();
            this.Acd_Offered_Course_Lecturer = new HashSet<Acd_Offered_Course_Lecturer>();
            this.Acd_Sched_Real = new HashSet<Acd_Sched_Real>();
            this.Acd_Sched_Real1 = new HashSet<Acd_Sched_Real>();
            this.Acd_Student_Supervision = new HashSet<Acd_Student_Supervision>();
            this.Acd_Thesis = new HashSet<Acd_Thesis>();
            this.Acd_Thesis1 = new HashSet<Acd_Thesis>();
            this.Acd_Thesis2 = new HashSet<Acd_Thesis>();
            this.Acd_Thesis3 = new HashSet<Acd_Thesis>();
            this.Acd_Thesis4 = new HashSet<Acd_Thesis>();
            this.Emp_Academic_Questioner_Result = new HashSet<Emp_Academic_Questioner_Result>();
            this.Emp_Attendance = new HashSet<Emp_Attendance>();
            this.Emp_Attendance_Allowance = new HashSet<Emp_Attendance_Allowance>();
            this.Emp_Attendance_Fingerprint = new HashSet<Emp_Attendance_Fingerprint>();
            this.Emp_Certificate_Competence = new HashSet<Emp_Certificate_Competence>();
            this.Emp_Dedication = new HashSet<Emp_Dedication>();
            this.Emp_Employee_Education = new HashSet<Emp_Employee_Education>();
            this.Emp_Employee_Family = new HashSet<Emp_Employee_Family>();
            this.Emp_Employee_Functional = new HashSet<Emp_Employee_Functional>();
            this.Emp_Employee_Other_Income = new HashSet<Emp_Employee_Other_Income>();
            this.Emp_Employee_Structural = new HashSet<Emp_Employee_Structural>();
            this.Emp_Fellowship = new HashSet<Emp_Fellowship>();
            this.Emp_Handbook = new HashSet<Emp_Handbook>();
            this.Emp_Journal = new HashSet<Emp_Journal>();
            this.Emp_kepangkatan = new HashSet<Emp_kepangkatan>();
            this.Emp_Loan = new HashSet<Emp_Loan>();
            this.Emp_Organization_Membership = new HashSet<Emp_Organization_Membership>();
            this.Emp_Patent = new HashSet<Emp_Patent>();
            this.Emp_Payroll_Attribute = new HashSet<Emp_Payroll_Attribute>();
            this.Emp_Payroll_Attribute1 = new HashSet<Emp_Payroll_Attribute>();
            this.Emp_Poster = new HashSet<Emp_Poster>();
            this.Emp_Postgraduate = new HashSet<Emp_Postgraduate>();
            this.Emp_Publication = new HashSet<Emp_Publication>();
            this.Emp_Publication_Oral = new HashSet<Emp_Publication_Oral>();
            this.Emp_Reduction_Other = new HashSet<Emp_Reduction_Other>();
            this.Emp_Research = new HashSet<Emp_Research>();
            this.Emp_Scientific_Creation = new HashSet<Emp_Scientific_Creation>();
            this.Emp_Social_Activity = new HashSet<Emp_Social_Activity>();
            this.Emp_Teach_Kbk_Count = new HashSet<Emp_Teach_Kbk_Count>();
            this.Emp_Teach_Kbk_Count_Resume = new HashSet<Emp_Teach_Kbk_Count_Resume>();
            this.Emp_Textbook = new HashSet<Emp_Textbook>();
            this.Emp_Topic = new HashSet<Emp_Topic>();
            this.Emp_Training = new HashSet<Emp_Training>();
            this.Emp_Vacation = new HashSet<Emp_Vacation>();
            this.Emp_Visiting_Expert = new HashSet<Emp_Visiting_Expert>();
            this.Mstr_Faculty = new HashSet<Mstr_Faculty>();
            this.Mstr_Faculty1 = new HashSet<Mstr_Faculty>();
            this.Mstr_Faculty2 = new HashSet<Mstr_Faculty>();
            this.Mstr_Faculty3 = new HashSet<Mstr_Faculty>();
            this.Mstr_Faculty4 = new HashSet<Mstr_Faculty>();
        }
    
        public int Employee_Id { get; set; }
        public string Nik { get; set; }
        public string Nip { get; set; }
        public string Name { get; set; }
        public string First_Title { get; set; }
        public string Last_Title { get; set; }
        public string Full_Name { get; set; }
        public string Birth_Place { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Address { get; set; }
        public Nullable<byte> Gender_Id { get; set; }
        public Nullable<byte> Religion_Id { get; set; }
        public Nullable<int> Identity_Type_Id { get; set; }
        public string Identity_Number { get; set; }
        public Nullable<int> Bank_Id { get; set; }
        public string Rec_Num { get; set; }
        public string Phone_Mobile { get; set; }
        public string Phone_Home { get; set; }
        public Nullable<byte> Employee_Status_Id { get; set; }
        public Nullable<byte> Blood_Type_Id { get; set; }
        public string Nbm { get; set; }
        public string Nidn { get; set; }
        public string Email_General { get; set; }
        public string Email_Corporate { get; set; }
        public string Role { get; set; }
        public Nullable<byte> Active_Status_Id { get; set; }
        public string Npwp { get; set; }
        public string Nik_Salary { get; set; }
        public string Photos { get; set; }
        public string Password { get; set; }
        public string Nik_Finger_Print { get; set; }
        public Nullable<int> Fingerprint_Id { get; set; }
        public string Document_Serdos { get; set; }
        public string Document_Serdos_Ext { get; set; }
        public Nullable<int> Work_Unit_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public string Employee_Role { get; set; }
        public string Forum_Role { get; set; }
        public string Payroll_Role { get; set; }
        public Nullable<int> internal_eksternal { get; set; }
        public string Rfid { get; set; }
        public Nullable<int> Card_Accepted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Class_Lecturer> Acd_Class_Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Lecturer> Acd_Course_Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Department_Lecturer> Acd_Department_Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course_Lecturer> Acd_Offered_Course_Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Real> Acd_Sched_Real { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Real> Acd_Sched_Real1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Supervision> Acd_Student_Supervision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Thesis> Acd_Thesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Thesis> Acd_Thesis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Thesis> Acd_Thesis2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Thesis> Acd_Thesis3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Thesis> Acd_Thesis4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Academic_Questioner_Result> Emp_Academic_Questioner_Result { get; set; }
        public virtual Emp_Active_Status Emp_Active_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Attendance> Emp_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Attendance_Allowance> Emp_Attendance_Allowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Attendance_Fingerprint> Emp_Attendance_Fingerprint { get; set; }
        public virtual Emp_Bank Emp_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Certificate_Competence> Emp_Certificate_Competence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Dedication> Emp_Dedication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Employee_Education> Emp_Employee_Education { get; set; }
        public virtual Emp_Employee_Status Emp_Employee_Status { get; set; }
        public virtual Emp_Work_Unit Emp_Work_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Employee_Family> Emp_Employee_Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Employee_Functional> Emp_Employee_Functional { get; set; }
        public virtual Mstr_Blood_Type Mstr_Blood_Type { get; set; }
        public virtual Mstr_Department Mstr_Department { get; set; }
        public virtual Mstr_Gender Mstr_Gender { get; set; }
        public virtual Mstr_Religion Mstr_Religion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Employee_Other_Income> Emp_Employee_Other_Income { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Employee_Structural> Emp_Employee_Structural { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Fellowship> Emp_Fellowship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Handbook> Emp_Handbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Journal> Emp_Journal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_kepangkatan> Emp_kepangkatan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Loan> Emp_Loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Organization_Membership> Emp_Organization_Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Patent> Emp_Patent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Payroll_Attribute> Emp_Payroll_Attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Payroll_Attribute> Emp_Payroll_Attribute1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Poster> Emp_Poster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Postgraduate> Emp_Postgraduate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Publication> Emp_Publication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Publication_Oral> Emp_Publication_Oral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Reduction_Other> Emp_Reduction_Other { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Research> Emp_Research { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Scientific_Creation> Emp_Scientific_Creation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Social_Activity> Emp_Social_Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Teach_Kbk_Count> Emp_Teach_Kbk_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Teach_Kbk_Count_Resume> Emp_Teach_Kbk_Count_Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Textbook> Emp_Textbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Topic> Emp_Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Training> Emp_Training { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Vacation> Emp_Vacation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Visiting_Expert> Emp_Visiting_Expert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Faculty> Mstr_Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Faculty> Mstr_Faculty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Faculty> Mstr_Faculty2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Faculty> Mstr_Faculty3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Faculty> Mstr_Faculty4 { get; set; }
    }
}
