//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_kepangkatan
    {
        public int Level_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Group_Id { get; set; }
        public string Sk_Number { get; set; }
        public Nullable<System.DateTime> Sk_Date { get; set; }
        public Nullable<System.DateTime> Date_Applied { get; set; }
        public Nullable<decimal> Salary_Main { get; set; }
        public bool Is_Continues { get; set; }
        public string Document_Name { get; set; }
        public string Document_Ext { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Emp_golongan Emp_golongan { get; set; }
    }
}
