//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_kunci_kehadiran
    {
        public int Semester { get; set; }
        public int Year_Id { get; set; }
        public int Month_Id { get; set; }
        public string Date { get; set; }
    }
}
