//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Family_Relation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_Family_Relation()
        {
            this.Emp_Employee_Family = new HashSet<Emp_Employee_Family>();
        }
    
        public int Family_Relation_Id { get; set; }
        public string Family_Relation_Name { get; set; }
        public Nullable<decimal> Rice_Allowance { get; set; }
        public Nullable<decimal> Hospitalization_Reduction { get; set; }
        public Nullable<decimal> Family_Allowance { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Employee_Family> Emp_Employee_Family { get; set; }
    }
}
