//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_import_gaji
    {
        public int id_import_gaji { get; set; }
        public int Month_Period { get; set; }
        public int Year_Period { get; set; }
        public string Nik { get; set; }
        public string Rec_Num { get; set; }
        public string Name { get; set; }
        public string jabatan { get; set; }
        public string golongan { get; set; }
        public string Status { get; set; }
        public string k_status { get; set; }
        public Nullable<int> p_status { get; set; }
        public string bagian { get; set; }
        public string senioritas { get; set; }
        public string fak { get; set; }
        public string nama_fak { get; set; }
        public string peserta { get; set; }
        public string Bank_Id { get; set; }
        public string Bank_Name { get; set; }
        public string Rec_Bank { get; set; }
        public Nullable<System.DateTime> tgl_masuk { get; set; }
        public Nullable<System.DateTime> tgl_akhir { get; set; }
        public Nullable<bool> Is_Married { get; set; }
        public Nullable<byte> Gender_Id { get; set; }
        public Nullable<bool> sumisjob { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<double> a_pokok { get; set; }
        public Nullable<double> a_struktur { get; set; }
        public Nullable<double> a_fungsi { get; set; }
        public Nullable<double> a_beras { get; set; }
        public Nullable<double> a_kel { get; set; }
        public Nullable<double> a_khusus { get; set; }
        public Nullable<double> a_lain { get; set; }
        public Nullable<double> a_hadir { get; set; }
        public Nullable<double> tot_sal { get; set; }
        public Nullable<double> p_astek { get; set; }
        public Nullable<double> p_komp { get; set; }
        public Nullable<double> p_Tax { get; set; }
        public Nullable<double> p_Other { get; set; }
        public Nullable<double> tot_pot { get; set; }
        public Nullable<double> net_sal { get; set; }
        public Nullable<double> d_exim { get; set; }
        public string d_eximke { get; set; }
        public Nullable<double> d_swajib { get; set; }
        public Nullable<double> d_srela { get; set; }
        public Nullable<double> d_aspinj { get; set; }
        public string d_ke { get; set; }
        public Nullable<double> d_bkop { get; set; }
        public string d_bkopke { get; set; }
        public Nullable<double> d_infaq { get; set; }
        public Nullable<double> d_asbank { get; set; }
        public string d_bankke { get; set; }
        public Nullable<double> d_keu { get; set; }
        public string d_keuke { get; set; }
        public Nullable<double> d_ibkp { get; set; }
        public Nullable<double> d_zakat { get; set; }
        public Nullable<double> d_hw { get; set; }
        public Nullable<double> d_arisan { get; set; }
        public Nullable<double> d_pensiun { get; set; }
        public Nullable<double> d_lain { get; set; }
        public Nullable<double> tot_d { get; set; }
        public Nullable<double> tot_net { get; set; }
        public string bulan { get; set; }
        public string kode_bln { get; set; }
        public string ref1 { get; set; }
        public string ref2 { get; set; }
        public Nullable<bool> tutup { get; set; }
        public Nullable<double> a_thr { get; set; }
        public Nullable<double> a_asur { get; set; }
        public Nullable<double> a_other { get; set; }
        public Nullable<System.DateTime> tgl_ajab { get; set; }
        public string no_rek_fix { get; set; }
    }
}
