//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Placement
    {
        public int Placement_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Work_Unit_Id { get; set; }
        public string Sk_Num { get; set; }
        public Nullable<System.DateTime> Sk_Date { get; set; }
        public System.DateTime Valid_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Work_Unit Emp_Work_Unit { get; set; }
    }
}
