//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Patent
    {
        public int Patent_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Category_Haki_Id { get; set; }
        public string Title { get; set; }
        public string Member { get; set; }
        public string Registration_Num { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public string Certificate_Num { get; set; }
        public string Short_Description { get; set; }
        public string Supporting_Document_Name { get; set; }
        public string Supporting_Document_Ext { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Category_Haki Emp_Category_Haki { get; set; }
        public virtual Emp_Employee Emp_Employee { get; set; }
    }
}
