//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Payroll_Attribute
    {
        public int Payroll_Attribute_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<decimal> Pks_Umy { get; set; }
        public Nullable<decimal> Arisan { get; set; }
        public Nullable<decimal> Simpanan_Wajib { get; set; }
        public Nullable<decimal> Simpanan_Sukarela { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<bool> Is_Pension_Contribution { get; set; }
        public Nullable<decimal> Dikti_Muhammadiyah { get; set; }
        public Nullable<decimal> Donatur_Hw { get; set; }
        public Nullable<decimal> Pkk { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Emp_Employee Emp_Employee { get; set; }
        public virtual Emp_Employee Emp_Employee1 { get; set; }
    }
}
