//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fnc_Profession_TAGIHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fnc_Profession_TAGIHAN()
        {
            this.Fnc_Profession_PAYMENT = new HashSet<Fnc_Profession_PAYMENT>();
        }
    
        public string Reff_Tagihan_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public string Biaya_Id { get; set; }
        public string JNS_ANGSURAN { get; set; }
        public Nullable<short> ANGSURAN_KE { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<short> MASA_BAYAR_KE { get; set; }
        public Nullable<System.DateTime> TGL_TAGIH { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Profession_PAYMENT> Fnc_Profession_PAYMENT { get; set; }
    }
}
