//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fnc_Profession_REFF_PAYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fnc_Profession_REFF_PAYMENT()
        {
            this.Fnc_Profession_PAYMENT = new HashSet<Fnc_Profession_PAYMENT>();
        }
    
        public string Reff_Payment_Id { get; set; }
        public System.DateTime Date_Of_Payment { get; set; }
        public int Branch_Id { get; set; }
        public string Bank_Id { get; set; }
        public short Cashier_Id { get; set; }
        public Nullable<System.DateTime> Print_Date { get; set; }
        public string Description { get; set; }
        public string Transaction_Type { get; set; }
        public string Store_Type { get; set; }
        public Nullable<decimal> Debet_Amount { get; set; }
        public string Sender_Rec { get; set; }
        public Nullable<System.DateTime> Send_Date { get; set; }
        public string BANK_PENGIRIM { get; set; }
        public string NAMA_PENGIRIM { get; set; }
        public string ALAMAT_PENGIRIM { get; set; }
        public string TRANSAKSI_ID { get; set; }
        public string NOMOR_ANJUNGAN { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<bool> IS_FETCHED { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Fnc_Bank Fnc_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Profession_PAYMENT> Fnc_Profession_PAYMENT { get; set; }
    }
}
