//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fnc_Reff_Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fnc_Reff_Payment()
        {
            this.Fnc_Student_Payment = new HashSet<Fnc_Student_Payment>();
        }
    
        public long Reff_Payment_Id { get; set; }
        public string Reff_Payment_Code { get; set; }
        public string Register_Number { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Bank_Id { get; set; }
        public Nullable<short> Cashier_Id { get; set; }
        public Nullable<System.DateTime> Print_Date { get; set; }
        public string Description { get; set; }
        public Nullable<short> Trans_Type_Id { get; set; }
        public string Reff_Old { get; set; }
        public string Reff_Resign { get; set; }
        public Nullable<short> Term_Year_Id { get; set; }
        public Nullable<int> Total_Amount { get; set; }
        public string Sender_Rec_Num { get; set; }
        public string Sender_Bank_Name { get; set; }
        public string Sender_Name { get; set; }
        public string Sender_Address { get; set; }
        public Nullable<System.DateTime> Sender_Date { get; set; }
        public string Transaction_Reff { get; set; }
        public string Channel_Num { get; set; }
        public string Cash_Type_Id { get; set; }
        public Nullable<bool> Is_Fetched { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Fnc_Bank Fnc_Bank { get; set; }
        public virtual Fnc_Cash_Type Fnc_Cash_Type { get; set; }
        public virtual Fnc_Trans_Type Fnc_Trans_Type { get; set; }
        public virtual Mstr_Term_Year Mstr_Term_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Student_Payment> Fnc_Student_Payment { get; set; }
    }
}
