//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fnc_Returns_Setting
    {
        public short Returns_Setting_Id { get; set; }
        public short Returns_Type_Id { get; set; }
        public short Cost_Item_Id { get; set; }
        public Nullable<decimal> Percent_Retur { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Fnc_Cost_Item Fnc_Cost_Item { get; set; }
        public virtual Fnc_Returns_Type Fnc_Returns_Type { get; set; }
    }
}
