//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mstr_Department()
        {
            this.Acd_App_Sk = new HashSet<Acd_App_Sk>();
            this.Acd_Course = new HashSet<Acd_Course>();
            this.Acd_Course_Classical = new HashSet<Acd_Course_Classical>();
            this.Acd_Course_Curriculum = new HashSet<Acd_Course_Curriculum>();
            this.Acd_Course_Identic = new HashSet<Acd_Course_Identic>();
            this.Acd_Curriculum_Entry_Year = new HashSet<Acd_Curriculum_Entry_Year>();
            this.Acd_Department_Lecturer = new HashSet<Acd_Department_Lecturer>();
            this.Acd_Grade_Department = new HashSet<Acd_Grade_Department>();
            this.Acd_Graduation_Best = new HashSet<Acd_Graduation_Best>();
            this.Acd_Offered_Course = new HashSet<Acd_Offered_Course>();
            this.Acd_Sched_Room = new HashSet<Acd_Sched_Room>();
            this.Acd_Sk_Publish = new HashSet<Acd_Sk_Publish>();
            this.Acd_Student = new HashSet<Acd_Student>();
            this.Acd_Student_KHS_DELETED = new HashSet<Acd_Student_KHS_DELETED>();
            this.Acd_Student_Out = new HashSet<Acd_Student_Out>();
            this.Acd_Student_Out1 = new HashSet<Acd_Student_Out>();
            this.Emp_Employee = new HashSet<Emp_Employee>();
            this.Fnc_Cost_Regular = new HashSet<Fnc_Cost_Regular>();
            this.Fnc_Cost_Regular_Up = new HashSet<Fnc_Cost_Regular_Up>();
            this.Fnc_Cost_Sched = new HashSet<Fnc_Cost_Sched>();
            this.Fnc_Cost_Timing = new HashSet<Fnc_Cost_Timing>();
            this.Fnc_Course_Cost_Sks = new HashSet<Fnc_Course_Cost_Sks>();
            this.Fnc_Course_Cost_Type = new HashSet<Fnc_Course_Cost_Type>();
            this.Mstr_Concentration = new HashSet<Mstr_Concentration>();
            this.Mstr_Curriculum_Applied = new HashSet<Mstr_Curriculum_Applied>();
            this.Mstr_Department_Class_Program = new HashSet<Mstr_Department_Class_Program>();
            this.Mstr_Department_Event_Sched = new HashSet<Mstr_Department_Event_Sched>();
        }
    
        public short Department_Id { get; set; }
        public string Department_Code { get; set; }
        public short Faculty_Id { get; set; }
        public short Education_Prog_Type_Id { get; set; }
        public string Department_Name { get; set; }
        public string Department_Name_Eng { get; set; }
        public string Department_Acronym { get; set; }
        public string Department_Dikti_Sk_Number { get; set; }
        public Nullable<System.DateTime> Department_Dikti_Sk_Date { get; set; }
        public Nullable<byte> Order_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_App_Sk> Acd_App_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course> Acd_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Classical> Acd_Course_Classical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Curriculum> Acd_Course_Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Identic> Acd_Course_Identic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Curriculum_Entry_Year> Acd_Curriculum_Entry_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Department_Lecturer> Acd_Department_Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Grade_Department> Acd_Grade_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Graduation_Best> Acd_Graduation_Best { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course> Acd_Offered_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Room> Acd_Sched_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sk_Publish> Acd_Sk_Publish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student> Acd_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_KHS_DELETED> Acd_Student_KHS_DELETED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Out> Acd_Student_Out { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Student_Out> Acd_Student_Out1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Employee> Emp_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular> Fnc_Cost_Regular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Regular_Up> Fnc_Cost_Regular_Up { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Sched> Fnc_Cost_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Cost_Timing> Fnc_Cost_Timing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Course_Cost_Sks> Fnc_Course_Cost_Sks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Course_Cost_Type> Fnc_Course_Cost_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Concentration> Mstr_Concentration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Curriculum_Applied> Mstr_Curriculum_Applied { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Department_Class_Program> Mstr_Department_Class_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Department_Event_Sched> Mstr_Department_Event_Sched { get; set; }
        public virtual Mstr_Education_Program_Type Mstr_Education_Program_Type { get; set; }
        public virtual Mstr_Faculty Mstr_Faculty { get; set; }
    }
}
