//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Out_Reason
    {
        public short Out_Reason_ID { get; set; }
        public Nullable<short> Out_Reason_Code { get; set; }
        public string Description { get; set; }
    }
}
