//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Course_Type
    {
        public Mstr_Course_Type()
        {
            this.Acd_Course = new HashSet<Acd_Course>();
        }
    
        public short Course_Type_Id { get; set; }
        public Nullable<short> Course_Type_Code { get; set; }
        public string Course_Type_Name { get; set; }
        public string Id_Character { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Acd_Course> Acd_Course { get; set; }
    }
}
