//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_JAM_SESSI
    {
        public short Year_Id { get; set; }
        public byte Term_Id { get; set; }
        public Nullable<short> Term_Year_ID { get; set; }
        public short Day_Id { get; set; }
        public Nullable<short> Sessi_Id { get; set; }
        public short JAM_KE { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> JAM_AWAL { get; set; }
        public Nullable<System.DateTime> JAM_AKHIR { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Mstr_JAM_KE Mstr_JAM_KE { get; set; }
    }
}
