//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mstr_Room()
        {
            this.Acd_Course_Classical = new HashSet<Acd_Course_Classical>();
            this.Acd_Course_Sched = new HashSet<Acd_Course_Sched>();
            this.Acd_Exam_Sched = new HashSet<Acd_Exam_Sched>();
            this.Acd_Offered_Course_Sched = new HashSet<Acd_Offered_Course_Sched>();
            this.Acd_Sched_Real = new HashSet<Acd_Sched_Real>();
            this.Acd_Sched_Room = new HashSet<Acd_Sched_Room>();
            this.Mstr_Room_Capacity = new HashSet<Mstr_Room_Capacity>();
        }
    
        public short Room_Id { get; set; }
        public string Room_Code { get; set; }
        public Nullable<short> Building_Id { get; set; }
        public string Room_Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Acronym { get; set; }
        public bool Is_Active { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Classical> Acd_Course_Classical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Sched> Acd_Course_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Exam_Sched> Acd_Exam_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Offered_Course_Sched> Acd_Offered_Course_Sched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Real> Acd_Sched_Real { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Sched_Room> Acd_Sched_Room { get; set; }
        public virtual Mstr_Building Mstr_Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Room_Capacity> Mstr_Room_Capacity { get; set; }
    }
}
