//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Curriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mstr_Curriculum()
        {
            this.Acd_Course_Curriculum = new HashSet<Acd_Course_Curriculum>();
            this.Acd_Curriculum_Entry_Year = new HashSet<Acd_Curriculum_Entry_Year>();
            this.Acd_Curriculum_PERUBAHAN = new HashSet<Acd_Curriculum_PERUBAHAN>();
            this.Mstr_Curriculum_Applied = new HashSet<Mstr_Curriculum_Applied>();
        }
    
        public short Curriculum_Id { get; set; }
        public string Curriculum_Code { get; set; }
        public string Curriculum_Name { get; set; }
        public Nullable<byte> Order_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Course_Curriculum> Acd_Course_Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Curriculum_Entry_Year> Acd_Curriculum_Entry_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acd_Curriculum_PERUBAHAN> Acd_Curriculum_PERUBAHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mstr_Curriculum_Applied> Mstr_Curriculum_Applied { get; set; }
    }
}
