//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Camaru_ID_GENERATION
    {
        public Nullable<int> START_NUMBER { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public long Camaru_Id { get; set; }
        public short Year_Id { get; set; }
        public string Entry_Period_Id { get; set; }
        public string Education_Group_Id { get; set; }
        public Nullable<int> sequence_index { get; set; }
        public string hasbeensold { get; set; }
        public string LOKASI_ID { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
