//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_QUA_FACTOR
    {
        public short Qua_Factor_Id { get; set; }
        public string Qua_Factor_Code { get; set; }
        public string Nim_Qua_Factor { get; set; }
    }
}
