//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Camaru_DELETED
    {
        public Nullable<int> SEQUENCE_INDEX { get; set; }
        public long Camaru_Id { get; set; }
        public short Year_Id { get; set; }
        public Nullable<short> Entry_Period_Id { get; set; }
        public string Full_Name { get; set; }
        public string Nick_Name { get; set; }
        public Nullable<byte> Gender_Id { get; set; }
        public Nullable<byte> Religion_Id { get; set; }
        public string Current_Address { get; set; }
        public Nullable<short> City_Id { get; set; }
        public Nullable<short> Province_Id { get; set; }
        public Nullable<short> Country_Id { get; set; }
        public string Picture { get; set; }
        public string Postal_Code { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public Nullable<short> Birth_Place_Id { get; set; }
        public Nullable<short> Birth_Country_Id { get; set; }
        public Nullable<short> Birth_Province_Id { get; set; }
        public string kab_lahir { get; set; }
        public string alamat_asal { get; set; }
        public string pos_asal { get; set; }
        public string telp_asal { get; set; }
        public string Phone_Home { get; set; }
        public string Phone_Mobile { get; set; }
        public Nullable<long> Prev_Camaru_Id { get; set; }
        public string Education_Group_Id { get; set; }
        public Nullable<short> Register_Status_Id { get; set; }
        public Nullable<float> Registration_Payment { get; set; }
        public string Registration_Paid { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public Nullable<System.DateTime> Registration_Time { get; set; }
        public string NIP_REGISTRATION { get; set; }
        public string IS_ULANG { get; set; }
        public string kuitansi_id { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public string Deleted_User { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
