//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Test_SCHEDULE
    {
        public short Term_Year_Id { get; set; }
        public short Entry_Period_Id { get; set; }
        public string Education_Group_Id { get; set; }
        public string Schedule_Code { get; set; }
        public string MATERI_TEST_ID { get; set; }
        public Nullable<System.DateTime> Test_Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> Start_Test_Time { get; set; }
        public Nullable<System.DateTime> End_Test_Time { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
