//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_offerred_edu_program
    {
        public short Faculty_Id { get; set; }
        public short Department_Id { get; set; }
        public string Education_Group_Id { get; set; }
        public short Available_Edu_Id { get; set; }
        public short Entry_Period_Id { get; set; }
        public short Year_Id { get; set; }
        public Nullable<decimal> min_sumbangan { get; set; }
        public short Class_Prog_Id { get; set; }
    }
}
