//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Application_FORM
    {
        public long Camaru_Id { get; set; }
        public short Year_Id { get; set; }
        public short Entry_Period_Id { get; set; }
        public Nullable<bool> Is_Sold { get; set; }
        public string Rooms_Id { get; set; }
        public Nullable<float> Registration_Payment { get; set; }
        public string Registration_Paid { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public string Nip_Registration { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public string Nip_Return { get; set; }
        public Nullable<System.DateTime> Registration_Time { get; set; }
        public Nullable<System.DateTime> Return_Time { get; set; }
        public Nullable<bool> Is_Ulang { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
