//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Universitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Camaru_Choice_DELETED
    {
        public string Year_Id { get; set; }
        public string Entry_Period_Id { get; set; }
        public string Camaru_Id { get; set; }
        public int Program_Choice_Id { get; set; }
        public Nullable<short> Faculty_Id { get; set; }
        public Nullable<short> Department_Id { get; set; }
        public string Education_Group_Id { get; set; }
        public string Available_Edu_Id { get; set; }
        public Nullable<float> Donation { get; set; }
        public string Is_Kurang { get; set; }
        public string GP_Choice_id { get; set; }
        public Nullable<short> Class_Prog_Id { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public string Deleted_User { get; set; }
        public Nullable<short> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<short> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
